### ISSUE TITLE
[infrastructure] Docker Compose replicas 기능 추가

### ISSUE THREAD

**Issue by seungdeok** [Frieeren/time-align#9]
## 📝 기능 설명
- Docker Compose의 `deploy.replicas` 옵션을 통한 서비스 스케일링 기능 추가
- Docker Swarm Mode
  - 로드 분산을 위한 동일 서비스 여러 인스턴스 실행
  - 고가용성 구성

## ✅ TODO

- [ ] docker compose 수정

## 📚 ETC
```yaml
services:
  api:
    image: myapp:latest
    deploy:
      replicas: 3
```
